spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_dev
    username: recipe_dev_user
    password: alex
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    datebase-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: alex_database_create.sql